### PR TITLE
Another way of finding the right version of lua lib

### PR DESCRIPTION
**Pull request by basvandervlies**
Inspired by the slurm code for slurm_lua.c

### CODE REVIEW

**Comment by kcgthb** [comment]
Hi @basvandervlies 
Thanks for the PR!

Just curious: did you find cases where `liblua.so` was not present on the system, but the versioned libs were? Maybe that's more of a Lua packaging issue in that case, isn't it? Trying to better understand what problem the PR is proposing to fix.
 
I'm also a bit worried that this piece of code will need to be update for every single new version of Lua, whereas the current approach seems to work and be version-independent.

What do you think?

**Comment by basvandervlies** [comment]
Hi Kilian

The default for this pull request is "liblua.so".  On debian/ubuntu like systems this does not exists. I had to made a symlink to make it work.  We can lnstall multiple Lua Dev versions 

That is why I patched the code. The code is the same as used in the slurm Lua source by schedmd. 

So for me this patch is fine

**Comment by kcgthb** [comment]
Ah, I see. Normally, in Debian (and derivatives), the `.so` symlink (without a version number) is provided by the `-dev` package: https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#development-files
> The development package should contain a symlink for the associated shared library without a version number.

So maybe this would just be solved by installing the `liblua5.3-dev` package, for instance?

Again, I'm concerned about maintainability here: having `ifdef`s to permit using different versions that behave differently is one thing, but exhaustively listing all the lib names for all the versions seems a bit fragile, either here or in the Slurm code, for that matter.

**Comment by basvandervlies** [comment]
Kilian that is not for liblua as on Debian like systems you can install multiple lua versions.  On my system I have installed:
 * liblua5.1-dev
 * liblua5.2-dev
 * liblua5.3-dev

Without it one of the dev's I can not compile the source. 

So there is no default `liblua.so`. This patch tries first the `liblua.so` and then the versioned libs. In the code there is already `ifdef` for different lua versions.  It is not that there are many new lua versions in a year ;-)

We also use the `job_submit.lua/cli_filter` in slurm. If the code was not present like the pull request it would not work either.

This ia what i found in the debian bug system:
 * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=781762

**Comment by kcgthb** [comment]
Ah right, that's true: Debian has considered Lua versions as completely different libraries and there's no `liblua.so`, but independent`liblua5.3.so`, `liblua5.4.so`, etc.
Ok, so that makes perfect sense now, thanks for providing that patch!

And if you ever want to provide Debian packaging files, they'll be very welcome! :D

**Comment by basvandervlies** [comment]
Thanks ;-). We use slurm tarball installations but when I have time I will provide a debian build directory

**Pull request merged**
